services:
  # Backend Service
  - type: web
    name: intern-portal-backend
    env: node
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false   # add in dashboard or via CLI (keeps it secret)

  # Frontend Service
  - type: web
    name: intern-portal-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://intern-portal-backend.onrender.com
